### ISSUE TITLE
bug 反馈

### ISSUE THREAD

**Issue by PayneSnow** [yeefun/notion-mark-manager#4]

**Comment by PayneSnow** [comment]
您好，感谢你开发了如此有用的Chrome插件。我在使用其他web app时，发现 Notion+ 标记管理器  会干扰我的输入，使得我输入的内容出现重复或者无法删除，或者同时出现了拼音和文字。不知道是不是bug。希望您能尽快修复。
测试写作网站：https://www.writeathon.cn/。之前 我在使用coda文档时也出现了类似问题，最近好像改善了。
![截屏2020-11-21 14 30 22](https://user-images.githubusercontent.com/51922806/99869458-1c3b3400-2c06-11eb-9450-4339ff548813.png)

**Comment by yeefun** [comment]
PayneSnow 你好，這款插件有設定只會在 Notion 的網域上起作用，因此不太可能會干擾到其它 Web APP 的操作。

想知道你所使用的瀏覽器？若你是使用 Chrome，查看這款插件有無起作用的方式是看它的圖標有沒有變成彩色，若是黑白則代表它在這個網站是沒起作用的。

**Comment by yeefun** [comment]
好幾個月沒人回應，故關閉。
